version: '2'

catalog:
  name: "gitpitch"
  version: "1.0.0"
  description: "Gitpitch server."
  minimum_rancher_version: v1.5.0
  # maximum_rancher_version:
  # upgrade_from: # The previous versions that this template can be upgraded from
  questions:
    - variable: "FQDN"
      label: "FQDN"
      description: |
        Domain name to expose on Traefik.
      default: "gitpitch.internal.ionpig.com"
      required: true
      type: "string"
services:
  gitpitch:
    start_on_create: true
