version: '2'

catalog:
  name: "helloworld"
  version: "1.0.0"
  description: Helloworld app!.
  minimum_rancher_version: v1.5.0
  # maximum_rancher_version:
  # upgrade_from: # The previous versions that this template can be upgraded from
  questions:
    - variable: "FQDN"
      label: "FQDN to use:"
      description: "Fully qualified domain name for traffic"
      default: helloworld.ionpig.com
      required: true
      type: "string"
services:
  helloworld:
    start_on_create: false
